=title Python: print stack trace after catching exception
=timestamp 2019-07-09T20:30:01
=indexes traceback, Exception
=status show
=books python
=author szabgab
=archive 1
=comments_disqus_enable 0

=abstract start
=abstract end

<include file="examples/python/stack_trace.py">


The upper stack-trace was printed by the <hl>traceback</hl> module. The lower one would
be if we did not catch it.

<code>
$ python examples/python/stack_trace.py
Traceback (most recent call last):
  File "examples/python/stack_trace.py", line 11, in <module>
    g()
  File "examples/python/stack_trace.py", line 4, in g
    f()
  File "examples/python/stack_trace.py", line 7, in f
    raise Exception("hi")
Exception: hi

---------------------
Traceback (most recent call last):
  File "examples/python/stack_trace.py", line 19, in <module>
    g()
  File "examples/python/stack_trace.py", line 4, in g
    f()
  File "examples/python/stack_trace.py", line 7, in f
    raise Exception("hi")
Exception: hi
</code>



